newsFeed/mainsite/urls.py
from django.urls import path
from . import views

app_name = 'mainsite'
urlpatterns = [
    path('search_title/', views.search_title, name='search_title'),
    path('results/', views.results, name='results'),
    path('search/', views.search, name='search'),
    path('source/<int:source_id>', views.view_source, name='source'),
    path('author/<int:author_id>', views.view_author, name='author'),
    path('article/<int:article_id>', views.view_article, name='article'),
    path('', views.index, name='index'),
]

newsFeed/newsFeed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('mainsite.urls', 'mainsite'), namespace='mainsite')),
    path('api/', include(('newsFeedAPI.urls', 'newsFeedAPI'), namespace='newsFeedAPI')),
    path('admin/', admin.site.urls),
]

newsFeed/mainsite/models.py
from django.db import models

# Create your models here.

newsFeed/mainsite/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render
from django.http import HttpResponse
import requests

from newsFeedAPI.models import Article
from newsFeedAPI.models import Source
from newsFeedAPI.models import Author


def index(request):
    list_articles = get_list_or_404(Article.objects.order_by('-publication_date'))
    ext_articles = requests.get('https://api.breakingapi.com/news?q=climate&type=headlines&locale=en-US&api_key=66406E7E3FAC4FA68DBD082E05DF04B1')
    #print(ext_articles.text)
    ext_articles_json = ext_articles.json()['articles']
    return render(request, 'mainsite/layout_page.html', {'title_page': 'NewsFeed',
                                                            'page': 'mainsite/index.html',
                                                            'list': list_articles,
                                                            'ext_articles': ext_articles_json})


def view_article(request, article_id):
    """
    :param request: article
    :param article_id: article.id
    :return: article with article_id
    """
    article = get_object_or_404(Article, id=article_id)

    return render(request, 'mainsite/layout_page.html', {'title_page': article.title,
                                                            'page': 'mainsite/article.html',
                                                            'article': article})


def view_source(request, source_id):
    list_articles = get_list_or_404(Article.objects.order_by('-publication_date'), source=source_id)

    return render(request, 'mainsite/layout_page.html', {'title_page': 'NewsFeed - source',
                                                            'page': 'mainsite/index.html',
                                                            'list': list_articles})


def view_author(request, author_id):
    list_articles = get_list_or_404(Article.objects.order_by('-publication_date'), author=author_id)

    return render(request, 'mainsite/layout_page.html', {'title_page': 'NewsFeed - author',
                                                            'page': 'mainsite/index.html',
                                                            'list': list_articles})


def search_title(request):
    list_articles = get_list_or_404(Article.objects.filter(title__contains=request.POST['title']))

    return render(request, 'mainsite/layout_page.html', {'title_page': 'NewsFeed - search title',
                                                            'page': 'mainsite/index.html',
                                                            'list': list_articles})


def search(request):
    articles = get_list_or_404(Article)
    authors = get_list_or_404(Author)
    sources = get_list_or_404(Source)

    date = {'month': range(13), 'day': range(32), 'year': ['2020', '2019', '2018']}

    objects = {'articles': articles, 'authors': authors, 'sources': sources, 'date': date}

    return render(request, 'mainsite/layout_page.html', {'title_page': 'NewsFeed - search',
                                                            'page': 'mainsite/form.html',
                                                            'objects': objects})


def results(request):

    entry_articles = Article.objects.all()

    if request.POST['input_title'] != 'Enter title':
        entry_articles = entry_articles.filter(title__contains=request.POST['input_title'])

    if request.POST['select_author'] != 'default':
        entry_articles = entry_articles.filter(author=request.POST['select_author'])

    if request.POST['select_source'] != 'default':
        entry_articles = entry_articles.filter(source=request.POST['select_source'])

    if request.POST['select_year_publication'] != 'default':
        entry_articles = entry_articles.filter(publication_date__year=request.POST['select_year_publication'])

    if request.POST['select_day_publication'] != 'default':
        entry_articles = entry_articles.filter(publication_date__day=request.POST['select_day_publication'])

    if request.POST['select_month_publication'] != 'default':
        entry_articles = entry_articles.filter(publication_date__month=request.POST['select_month_publication'])

    list_articles = list(entry_articles)

    return render(request, 'mainsite/layout_page.html', {'title_page': 'newsFeed - results',
                                                            'page': 'mainsite/index.html',
                                                            'list': list_articles})

newsFeed/mainsite/templates/mainsite/article.html
<div class="row">
    <div class="col-2">
        <img class="img-fluid" alt="illustrating image" src="{{ article.image_link }}">
    </div>
    <div class="col-10">
        <h2>{{ article.title }}</h2>
        <h4>{{ article.description }}</h4>

        <p class="font-italic">published in {{ article.source }}, and written by {{ article.author }}</p>
    </div>
</div>

<hr/>

<div>
    <p>{{ article.content }}</p>
</div>

newsFeed/mainsite/templates/mainsite/form.html
<h1>Forms</h1>

<hr/>

<form action="{% url 'mainsite:results' %}" method="post">
    {% csrf_token %}

    <!-- options for title -->
    <div class="form-group">
        <label for="input_title">Article's title</label>
        <input type="text" name="input_title" id="input_title" class="form-control" placeholder="Enter title">
    </div>

    <!-- Select options for author -->
    <div class="form-group">
        <label for="select_author">Select Author</label>
        <select name="select_author" id="select_author" class="form-control">
            <option class="default" value="default">-- no author selected --</option>
            {% for author in objects.authors %}
                <option value="{{ author.id }}"> {{ author }} </option>
            {% endfor %}
        </select>
    </div>

    <!-- Select options for source -->
    <div class="form-group">
        <label for="select_source">Select Source</label>
        <select name="select_source" id="select_source" class="form-control">
            <option class="default" value="default">-- no source selected --</option>
            {% for source in objects.sources %}
                <option value="{{ source.id }}"> {{ source }} </option>
            {% endfor %}
        </select>
    </div>

    <!-- Select options for publication date -->
    <div class="form-row">
        <div class="form-group col">
            <label for="select_day_publication">Day</label>
            <select name="select_day_publication" class="form-control">
                <option class="default" value="default">-- no day selected --</option>
                {% for day in objects.date.day %}
                    <option> {{ day }} </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group col">
            <label for="select_month_publication">Month</label>
            <select name="select_month_publication" class="form-control">
                <option class="default" value="default">-- no month selected --</option>
                {% for month in objects.date.month %}
                    <option> {{ month }} </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group col">
            <label for="select_year_publication">Year</label>
            <select name="select_year_publication" class="form-control">
                <option class="default" value="default">-- no year selected --</option>
                {% for year in objects.date.year %}
                    <option> {{ year }} </option>
                {% endfor %}
            </select>
        </div>
    </div>

    <button class="btn btn-success" type="submit">Submit</button>
</form>

newsFeed/mainsite/templates/mainsite/index.html
Nos articles
<hr>
{% for article in list %}
    <div class="card border-dark mt-1">
        <div class="card-body row">
            <div class="col-2">
                <img class="img-fluid" alt="illustrating image" src="{{ article.image_link }}">
            </div>
            <div class=" col-10">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.description }}</p>
                <a href="{% url 'mainsite:article' article.id %}" class="stretched-link">Voir l'article</a>
            </div>
        </div>
    </div>
{% endfor %}
<br>
Plus d'Articles
<hr>
{% for ext_article in ext_articles %}
    <div class="card border-dark mt-1">
        <div class="card-body row">
            <div class="col-2">
                <img class="img-fluid" alt="illustrating image" src="{{ ext_article.primary_image_link }}">
            </div>
            <div class=" col-10">
                <h5 class="card-title">{{ ext_article.title }}</h5>
                <p class="card-text">{{ ext_article.snippet }}</p>
                <a href="{{ ext_article.link }}" class="stretched-link" target="_blank">Voir l'article</a>
            </div>
        </div>
    </div>
{% endfor %}

newsFeed/mainsite/templates/mainsite/layout_page.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'mainsite/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mainsite/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mainsite/fontawesome.all.min.css' %}">

        <title>{{ title_page }}</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'mainsite:index' %}">NewsFeed</a>

        <form action="{% url 'mainsite:search_title' %}" class="form-inline" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2" name="title" id="title" type="search" placeholder="Search in titles" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
            <a class="btn btn-danger ml-1" href="{% url 'mainsite:search' %}" role="button">Advanced search</a>
        </form>
    </nav>

    <div class="container p-3 p-md-5">

        {% if page %}
            {% include page %}
        {% endif %}

    </div>
  </body>
</html>